export const translation: { [index: string]: { [key: string]: string } } = {
  en: {
    accessibilityMenu: 'Accessibility Menu',
    reset: 'Reset',
    bigCursor: 'Big Cursor',
    readingMask: 'Reading Mask',
    hideImage: 'Hide Image',
    highlightLink: 'Highlight Link',
    increaseLetterSpace: 'Increase Letter Space',
    increaseLineHeight: 'Increase Line Height',
    darkContrast: 'Dark Contrast',
    lightContrast: 'Light Contrast',
    invertColor: 'Invert Color',
    pageStructure: 'Page Structure',
    leftAlign: 'Left Align',
    rightAlign: 'Right Align',
    lowSaturation: 'Low Saturation',
    highSaturation: 'High Saturation',
    desaturate: 'Desaturate',
    links: 'Links',
    headings: 'Headings',
    language: 'Language',
    english: 'English',
    german: 'German',
    currentLanguage: 'English'
  },
  de: {
    accessibilityMenu: 'Barrierefreiheit-Menü',
    reset: 'Zurücksetzen',
    bigCursor: 'Großer Cursor',
    readingMask: 'Lesemaske',
    hideImage: 'Bild ausblenden',
    highlightLink: 'Link hervorheben',
    increaseLetterSpace: 'Buchstabenabstand vergrößern',
    increaseLineHeight: 'Zeilenhöhe vergrößern',
    darkContrast: 'Dunkler Kontrast',
    lightContrast: 'Heller Kontrast',
    invertColor: 'Farben umkehren',
    pageStructure: 'Seitenstruktur',
    leftAlign: 'Links ausrichten',
    rightAlign: 'Rechts ausrichten',
    lowSaturation: 'Geringe Sättigung',
    highSaturation: 'Hohe Sättigung',
    desaturate: 'Entsättigen',
    links: 'Links',
    headings: 'Überschriften',
    language: 'Sprache',
    english: 'Englisch',
    german: 'Deutsch',
    currentLanguage: 'Englisch'
  }
};
