export const enum Types {
  BIG_CURSOR = 'BIG_CURSOR',
  READING_MASK = 'READING_MASK',
  HIGHLIGHT_LINK = 'HIGHLIGHT_LINK',
  HIDE_IMAGE = 'HIDE_IMAGE',
  INCREASE_LETTER_SPACE = 'INCREASE_LETTER_SPACE',
  INCREASE_LINE_HEIGHT = 'INCREASE_LINE_HEIGHT',
  DARK_CONTRAST = 'DARK_CONTRAST',
  LIGHT_CONTRAST = 'LIGHT_CONTRAST',
  INVERT_COLOR = 'INVERT_COLOR',
  PAGE_STRUCTURE = 'PAGE_STRUCTURE',
  LEFT_ALIGN = 'LEFT_ALIGN',
  RIGHT_ALIGN = 'RIGHT_ALIGN',
  LOW_SATURATION = 'LOW_SATURATION',
  HIGH_SATURATION = 'HIGH_SATURATION',
  DESATURATE = 'DESATURATE'
}

export type Feature = {
  feature: boolean;
  handler: () => void;
  icon: JSX.Element;
  featureName: string;
  text: string;
}
